### ISSUE TITLE
unwrap message

### ISSUE THREAD

**Issue by mathroc** [hoaproject/Option#10]
`return $this->expect('Unwrap a null value.');`

should `null` appear in the error message ? maybe something with None instead so that `$this->value` remains an implementation details ?

I saw that the class comment says 

> `None` which is the equivalent of `null`

so it might be that null is not only an implementation detail

**Comment by Hywan** [comment]
Rust `std::option::Option` panicked with the following message:

> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:33

It fits with your suggestion. I will make a PR.

**Comment by Hywan** [comment]
@mathroc Please, could you review #12? Thanks!
