### ISSUE TITLE
php version 7.1?

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Option#11]
any reason to require 7.1 instead of 7.0?

**Comment by Hywan** [comment]
Because this is what we agreed on :-). cc @hoaproject/hoackers

**Comment by Grummfy** [comment]
for me it's was not clear witch version we agree on ;) but you make a clarification on https://github.com/hoaproject/Central/issues/74

**Comment by Hywan** [comment]
:heart:

I wasn't able to find a clear statement but we discussed about it during a Hoa Virtual Meeting.
