### ISSUE TITLE
Correction Documentation

### ISSUE THREAD

**Issue by maitrepylos** [hoaproject/Option#8]
Salut,
Il manque un 'a' à assert dans la ligne suivante dans le README : 
```php
ssert(None()->unwrap()); // will throw a `RuntimeException`.
```

J'ai voulu modifier moi même; mais je ne peux pas.
@+

**Comment by Hywan** [comment]
Hello,

Thank for the bug report! Do you want to do a PR?

**Comment by Hywan** [comment]
Fixed by https://github.com/hoaproject/Option/commit/a4daf8836f58912512672ad9ba04d282a57e3370. Thanks!
